[QA] 출처 미등록했을 때 대응 가이드 추가
mash-up-kr/ppac-android pull request #185
Opened 2024-08-06 15:29 UTC by hj1115hj

### Issue
- close #181

### 작업 내역 (Required)
- https://www.notion.so/Quality-Assurance-Board-037419ad68dd4b068e82b8cf6217bcae?p=2963f1fb630c4ddaa06fa0423e719dea&pm=s
- 
### Review Point (Required)

### Screenshot
![KakaoTalk_20240807_002844148](https://github.com/user-attachments/assets/352a03c9-f258-43b1-a03e-1162a152ed4f)

2024-08-07 06:31 UTC, ze-zeh approved these changes
LGTM~

2024-08-08 13:39 UTC, JaesungLeee approved these changes

2024-08-08 13:39 UTC, JaesungLeee commented on feature/detail/src/main/java/team/ppac/detail/component/DetailContent.kt
> +            "출처 : ".plus(sourceDescription.truncateDisplayedString(32))
쫌 더 Kotlin 스럽게.. 가보시죵

2024-08-11 07:13 UTC, hj1115hj commented on feature/detail/src/main/java/team/ppac/detail/component/DetailContent.kt
> +            "출처 : ".plus(sourceDescription.truncateDisplayedString(32))
```
 sourceDescription.takeIf { it.isNotEmpty() }
            ?.let { "출처 : ${it.truncateDisplayedString(32)}" }
            ?: sourceDescription,
```
요렇게 변경했습니당~

2024-08-11 08:15 UTC, JaesungLeee requested changes

2024-08-11 08:15 UTC, JaesungLeee commented on feature/detail/src/main/java/team/ppac/detail/component/DetailContent.kt
> +            ?: sourceDescription,
요거대로 수정된게 맞나..??

<img width="592" alt="image" src="https://github.com/user-attachments/assets/33dbbdc5-5fd3-436c-a1fe-56b493c5f051">

2024-08-11 12:08 UTC, hj1115hj commented on feature/detail/src/main/java/team/ppac/detail/component/DetailContent.kt
> +            ?: sourceDescription,
"" 일때 text가 보일까바 걱정했는뎅 ""일때 영역 삭제되더라궁~

2024-08-11 13:18 UTC, JaesungLeee approved these changes

2024-08-11 13:18 UTC, JaesungLeee commented on feature/detail/src/main/java/team/ppac/detail/component/DetailContent.kt
> +    }
NIT : 요런식으로 간단하게 갈 수도 있을 것 같아서 제안해봤습니당 ㅋㅋ
```suggestion
    if (sourceDescription.isNotEmpty()) {
        Spacer(modifier = Modifier.height(11.dp))
        Text(
            modifier = Modifier.mapTextSkeletonModifierIfNeed(
                isLoading = isLoading,
                height = 15.dp,
            ),
            text = "출처 : ${it.truncateDisplayedString(32)}",
            color = FarmemeTheme.textColor.assistive,
            style = FarmemeTheme.typography.body.xSmall.medium,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
        )
    }
```

2024-08-11 14:03 UTC, hj1115hj commented on feature/detail/src/main/java/team/ppac/detail/component/DetailContent.kt
> +    }
@JaesungLeee  수정완룡!!

2024-08-12 13:44 UTC, EvergreenTree97 approved these changes

2024-08-12 13:44 UTC, merged