[Feat] 디자인 시스템 구축
mash-up-kr/ppac-android pull request #21
Opened 2024-06-18 11:16 UTC by EvergreenTree97

### Issue
- close #ISSUE_NUMBER

### 작업 내역 (Required)

### Review Point (Required)
- none

### Screenshot
Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

### 관련 링크
-

2024-06-21 14:03 UTC, evergreentree97 reviewed
고생많읐으요~

2024-06-21 14:03 UTC, evergreentree97 commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +            .clickable { onClick() },
clickable(onclick = onclick) 하면 람다 생성 비용을 한번 아낄 수 있어요~ 앱에 중요한 영향을 끼치진 않슴다

2024-06-21 14:06 UTC, hj1115hj approved these changes
질문남겨놨우용 코드짜느라 고생했어용~ preview있으면 좋을거 가타염!

2024-06-21 14:06 UTC, hj1115hj commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +    size: Dp = 50.dp,
사이즈 이렇게 하기로 한거구나 굿! 👍

2024-06-21 14:06 UTC, hj1115hj commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +            .wrapContentSize()
이거 안붙여둥 wrap content아닌가용?

2024-06-21 14:06 UTC, hj1115hj commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +            .padding(15.dp),
padding이 size 위, 아래 있으때 차이가 뭐가 있을까용

2024-06-21 14:06 UTC, hj1115hj commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +    isActive: Boolean,
active는 처음에 default값 있는게 좋지않을까? default값 없이 사용한 이유가있을까용?

2024-06-21 14:06 UTC, hj1115hj commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/foundation/Icon.kt
> +object FarmemeIcon {
왓 진짜 고생했다 깔끔!!

2024-06-21 14:07 UTC, EvergreenTree97 commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +fun FarmemeChip(
컴포넌트들 시간 괜찮으면 프리뷰 함께 작성해주시면 다른사람 수정하거나 볼 때 편할 것 같아요~

2024-06-21 14:09 UTC, EvergreenTree97 commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +        verticalAlignment = Alignment.CenterVertically,
horizontalArrangement = Arrangment.spacedBy(4.dp) 
요렇게 줄 수도 있는데 취향껏 하면 될 것 같아요~

2024-06-21 14:14 UTC, EvergreenTree97 commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +    onClick: () -> Unit = { },
<img width="1007" alt="image" src="https://github.com/mash-up-kr/ppac-android/assets/70064912/c8cd77c0-2523-46b3-9953-dbe87e701d3d">
컴포저블 람다를 가장 뒤에 순서를 두어, 후행 람다로 사용될 수 있도록 하는것을 권장합니다!
compose guidline 참고~

```kotlin
FarmemeFilledbutton { 
    Icon()
}
```

2024-06-21 14:16 UTC, EvergreenTree97 commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +    val (backgroundColor, textStyle, textColor) = if (isActive) {
👍

2024-06-21 14:18 UTC, EvergreenTree97 commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/foundation/Radius.kt
> +enum class FarmemeRadius(val shape: RoundedCornerShape) {
👍

2024-06-21 14:19 UTC, hj1115hj commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +    onClick: () -> Unit = { },
https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md

2024-06-21 14:42 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +            .clickable { onClick() },
오 새롭게 하나 알아갑니다~~

2024-06-21 14:43 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +        verticalAlignment = Alignment.CenterVertically,
참고하겠습니다~!

2024-06-21 14:45 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +    onClick: () -> Unit = { },
정리 : 우리 플젝에서는 modifier를 가장 첫번째 파라미터로 두고, 람다는 가장 마지막, 컴포저블 람다는 람다 바로 위, 나머지 파라미터들은 자율~

2024-06-21 14:47 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/foundation/Icon.kt
> +object FarmemeIcon {
굳굳~!

2024-06-21 14:47 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +    isActive: Boolean,
따로 이유는 없는데 false로 default값을 주는게 좋아보여요! 반영하겠슴당

2024-06-21 14:53 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +            .wrapContentSize()
오!!!! 몰랐어용!!!!!!! 배워갑니다!!!!! 저건 지워놓을게유!!

2024-06-21 14:59 UTC, JaesungLeee requested changes
![image](https://github.com/mash-up-kr/ppac-android/assets/51078673/994ffa23-8e7e-43be-8f6f-bf16f1d3c365)

2024-06-21 14:59 UTC, JaesungLeee commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +            .clickable { onClick() },
수수수수퍼노바

2024-06-21 14:59 UTC, JaesungLeee commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/foundation/DesignToken.kt
> +    val brandassistive: Color = Orange10,
brandAssistive?

2024-06-21 14:59 UTC, JaesungLeee commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +    isActive: Boolean,
어그리~ 그리고 Active/Inactive라는 네이밍으로 디자이너가 전달해주긴 했지만 컴포즈에서는 enabled라는 네이밍으로 판단하는게 좋을듯용~!

2024-06-21 14:59 UTC, JaesungLeee commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +    }
고민 많이하고 작성한 코드처럼 보여서 매우 감개무량 ㄷㄷ
컴포넌트 Theming 관련해서 하나 피드백 하자면 아래처럼 작성할 수도 있을 것 같아요~

``` kotlin
@Stable
interface ChipColors {
    @Composable
    fun backgroundColor(enabled: Boolean): State<Color>

    @Composable
    fun contentColor(enabled: Boolean): State<Color>
}

@Immutable
private class FarmemeChipColors(
    private val backgroundColor: Color,
    private val contentColor: Color,
    private val disabledBackgroundColor: Color,
    private val disabledContentColor: Color,
) : ChipColors {
    @Composable
    override fun backgroundColor(enabled: Boolean): State<Color> {
        return rememberUpdatedState(if (enabled) backgroundColor else disabledBackgroundColor
    }

    ...
}

@Composable
fun farmemeChipColors(
    backgroundColor: Color = /* disabled일때 색상 */,
    contentColor: Color = /* disabled일때 색상 */,
    disabledBackgroundColor: Color = /* disabled일때 색상 */,
    disabledContentColor: Color = /* disabled일때 색상 */,
): ChipColors = FarmemeChipColors(
    backgroundColor = backgroundColor,
    contentColor = contentColor
)

/** 사용할 컴포넌트에서 ~ **/
val colors = farmemeChipColors()
val backgroundColor by colors.backgroundColor(enabled = enabled)
val textColor by colors.contentColor(enabled = enabled)
```
Ref. [Material Button#ButtonColors](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/Button.kt;l=279?q=ButtonColors)

2024-06-21 15:16 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +fun FarmemeChip(
추가했습니당~

2024-06-21 15:17 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +    isActive: Boolean,
@JaesungLeee 반영할게요~!

2024-06-21 15:17 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/foundation/DesignToken.kt
> +    val brandassistive: Color = Orange10,
수정했습니당~

2024-06-21 15:38 UTC, JaesungLeee commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +    isActive: Boolean,
@ze-zeh enabled 값은 기본적으로 활성화를 해놓도록 true로 하는게 좋을듯용!

2024-06-24 13:24 UTC, EvergreenTree97 commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/chip/Chip.kt
> +    }
@Composable
fun Chip(
    chipColors: ChipColors = defaultChipColors()
){
    if(enabled){
        val contentColor: Color,
        val backgroundColor: Color,
    }else{
        val disabledContentColor: Color,
        val disabledBackgroundColor: Color,
    }
}

data class ChipColors(
    val contentColor: Color,
    val disabledContentColor: Color,
    val backgroundColor: Color,
    val disabledBackgroundColor: Color,
)

@Composable
fun defaultChipColors() = ChipColors(
    FarmemeTheme.backgroundColor.brand,
    FarmemeTheme.backgroundColor.assistive,
    FarmemeTheme.backgroundColor.brand,
    FarmemeTheme.backgroundColor.assistive,
)

요러코롬 간소화 해서 쓰는 방향은 어떠실까요?

2024-06-24 14:20 UTC, JaesungLeee approved these changes
![image](https://github.com/mash-up-kr/ppac-android/assets/51078673/dbf1a1dc-f9b8-4cb7-b614-0b1e50b32fd4)
잠금해제 해드립니다~

2024-06-24 14:21 UTC, EvergreenTree97 commented
LGTM

2024-06-24 14:22 UTC, merged

2024-06-27 13:41 UTC, ze-zeh commented on core/designsystem/src/main/kotlin/team/ppac/designsystem/component/button/Button.kt
> +            .padding(15.dp),
오늘 이 주제로 발표 갈겼는데 담에 설명할게용~