[feat] toolbar 디자인 시스템 구현
mash-up-kr/ppac-android pull request #37
Opened 2024-06-29 11:19 UTC by hj1115hj

### Issue
- close #ISSUE_NUMBER

### 작업 내역 (Required)
- tool bar 작업

### Review Point (Required)
- 매번 아이콘 입력해주는 방식 아닌 만들어진거 사용하도록 한번더 wrap 해봤습니당

### Screenshot
Before | After
:--: | :--:
<img src="" width="300"
<img width="464" alt="스크린샷 2024-06-29 오후 8 17 23" src="https://github.com/mash-up-kr/ppac-android/assets/23455686/5e32adf8-d949-4157-907d-58ae040bf5a6">
 /> | <img src="" width="300" />

### 관련 링크
-

2024-06-29 11:41 UTC, JaesungLeee requested changes
Issue 일단 생성부탁~
전체적인 구조가 일단 기존에 채택한 방식들이랑 많이 달라서 구두로 설명하겠습니당

2024-06-29 13:49 UTC, JaesungLeee approved these changes
구심니다~

2024-06-30 08:26 UTC, EvergreenTree97 approved these changes
깔끔하네용! LGTM

2024-07-01 14:16 UTC, JaesungLeee commented
LG트윈스 TM~

2024-07-02 06:49 UTC, ze-zeh approved these changes
LGTM~ 고생했어용

2024-07-02 10:30 UTC, merged